### ISSUE TITLE
Class naming conventions

### ISSUE THREAD

**Issue by mjanjic01** [infinum/frontend-handbook#13]
Class naming conventions should be added to the JavaScript/React books.
This (for now) includes:

#### _private_ properties
Some usual patterns are prefixing private properties/methods with `_`
#### event handlers in react methods
Some eslint rules for prefixing/suffixing the methods with `handler`/`handle`
Combination of this rule with the `_` should also be taken into consideration.

Please add any conventions you might find useful and discuss the proposed ones above
@andreicek , your input regarding the handler name linting is welcome

**Comment by fvoska** [comment]
I personally do not agree with prefixing private properties/methods with `_`. What does it achieve, other than make the code uglier?

If there are issues with telling private and public properties/method apart on a glance, I think that the better solution is to force defining accessors at all times (`"member-access": true` to avoid situations where no accessor is defined and then there can be confusion if it is public or private).

Only case where I would prefix `_` is if I have a public getter and private setter for some private prop:
```ts
class Foo {
  private _bar: string;
  public get bar(): string { return this._bar; }
}
```

I don't like it here either, but it is the only option since in TS `Accessors for the same member name must specify the same accessibility`. In C# this is much nicer, there you do not need `_` prefix:
```csharp
class Foo {
  public string bar { get; private set; }
}
```

**Comment by DarkoKukovec** [comment]
@fvoska this discussion is mostly about js, where we don't have other ways of determining if something is meant to be private or public.

I generally like to have `_` on private methods, but agree that adding `handler` to the name of event handlers adds some consistency. Not sure if I would like one or the other more, but I don't like the idea of using them together :/

**Comment by fvoska** [comment]
For click handler prefix, in Angular we usually prefix handler methods with `on`. `<div (click)="onMyDivClick()"></div>`. I guess we could change that to `myDivClickHandler`.

**Comment by DarkoKukovec** [comment]
In our last discussion we concluded that in both Angular and React the general convention is to use `onSomethingClick` (and generally avoid `onClick`). I'll update the handbook to address that. Also, no need to use `_` since we're using TypeScript anyway.

**Comment by andreicek** [comment]
Closing as stale.
