### ISSUE TITLE
Code consistency

### ISSUE THREAD

**Issue by leobrdar** [infinum/frontend-handbook#14]
### Problem
Although we have style guide and code reviews, I think we can all agree that the code on most projects is still inconsistent. People don't tend to spend much time studying style guide and code reviews are usually done quickly and include too much code so reviewer can't go into details. Even if it wasn't like that, leaving formatting and consistency to humans seems wrong. Not to mention that the developer shouldn't lose time and worry about how the code is formatted.

### Possible solution
One possible solution is **[prettier](https://prettier.io/)** . 
[Why prettier?](https://prettier.io/docs/en/why-prettier.html) 

- Developer just writes code and doesn't care about format. 
- All code on all projects is formatted 100% identically. 
- New collegues don't have to worry about style guide and formatting rules

However it's very opinioned and in some ways doesn't fully follow our style guide. Are we ready to pay this price? 

### What now?
My idea is that we discuss if this is acceptable. One way we can do this is by writting down all internal formatting rules that prettier breaks. You can easily paste any code to [prettier playground](https://prettier.io/playground/) and set options, to get prettified output. 

_Other solutions are also welcome._           
<br />

Let's make our code pretty!  🙏 💅 😄

**Comment by mjanjic01** [comment]
> Nobody loves what prettier does to their syntax
> 
> Everyone loves what prettier does to their coworkers' syntax

**Comment by DarkoKukovec** [comment]
I'm guessing we could use something like https://github.com/prettier/prettier-eslint and https://github.com/azz/prettier-tslint to bring it close to our styleguide.

The part I'm worried about is that the tools can fail on the user devices (and won't even work if they're not set up correctly). That's why I wouldn't want to rely only on tooling 100% (with that in mind, I was also thinking about running linters on CI for all projects, not only on precommit).

**Comment by leobrdar** [comment]
> I'm guessing we could use something like https://github.com/prettier/prettier-eslint and https://github.com/azz/prettier-tslint to bring it close to our styleguide.

Ideally, we wouldn't even need that as usually the best practice is to disable all linter rules about code formatting when using some other formatter. Linters main purpose isn't code formatting. However, if we are strictly bound by some internal formatting rules defined by the eslint/tslint, then that would be the way to go. 

> tools can fail on the user devices

Can you explain this part, please? Fail in which way? 

> won't even work if they're not set up correctly

I don't think the setup would be too complicated. It usually takes me from few to several minutes to install, setup and run prettier with linter. That process could also be added to the handbook and boilerplates we use, so the possibility for the wrong config is minimal.

>  I wouldn't want to rely only on tooling 100% 

Of course, code reviews would still be needed.

**Comment by DarkoKukovec** [comment]
> Ideally, we wouldn't even need that as usually the best practice is to disable all linter rules about code formatting
We have a number of rules that are not strictly formating related (e.g. a11y), but also most of the styleguide is that way because initially we started with a styleguide similar to Airbnb (we just finished our first version of styleguide like a week before airbnb was published and it was 95% similar), and changing the way in which 20-25 developers write the code can not be done overnight. Also, since most of the rules are subjective, I wouldn't want to force people to write in one way just because prettier says so, but no one else wants to.

> tools can fail on the user devices
We had some situations where linters failed for no apearent reason

> I don't think the setup would be too complicated
If all setup is on the project side it isn't an issue, but if developers are supposed to set up something that is device specific, then this can become a problem (wrong setup, they forget, ...)

**Comment by mjanjic01** [comment]
>Developer just writes code and doesn't care about format.

If someone doesn't take care to format their code correctly it brings in question the general care they took writing it and how much of it was revised before committing it.

Formatting is subjective and I don't think prettier covers **all** of the formatting rules you might want to enforce, consistency at that level doesn't seem very important as we should all have a similar idea of what pretty code should look like. Consistent code will only appear if you are the only one writing it.

**Comment by safo6m** [comment]
I'm against using tools like prettier because I'm trying to write code the way I think is the most readable.

When multiple people are working on the same codebase, the code probably won't be 100% consistent and I don't think that this is an issue. 
I agree that some of the stuff (like spaces in curly brackets, line lenght, ...) should be enforced and those rules should cover most of our use cases.

> Developer just writes code and doesn't care about format.
I don't want to work with someone who doesn't care about formatting.

> New collegues don't have to worry about style guide and formatting rules
New collegues have to worry about the styleguides the most. If they won't use good practices in the beginning, they won't learn them at all.

**Comment by NinoMaj** [comment]
Here are my two cents. I am all for Prettier, but I believe Leo mentioned wrong reasons for it:
> Developer just writes code and doesn't care about format.
> New colleagues don't have to worry about style guide and formatting rules

When I use eslint it is not like I don't care what I write because eslint will fix it. Same thing will be with Prettier.

On the link Leo provided there are good arguments for Prettier so I won't repeated here, but most important is less time spent discussing code formatting.
