### ISSUE TITLE
NPM vs. Yarn

### ISSUE THREAD

**Issue by andreicek** [infinum/frontend-handbook#24]
Sparked by learnQuery we started the discussion should we pick `yarn` or `npm`. Currently create-react-app, the main reason we used yarn supports npm. The main point of this discussion is what package manager will be our new default. I think we can all agree on having a stable standard for new and existing projects.

In order to prevent discussion about performance I've ran some tests.
<details><summary>NPM Performance</summary>

```
andrei@macbookpro /t/react> npm --version
6.6.0
andrei@macbookpro /t/react> time npm init react-app my-app                                                                                                                [2/1816]
npx: installed 63 in 1.784s

Creating a new React app in /private/tmp/react/my-app.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts...

yarn add v1.12.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 5 new dependencies.
info Direct dependencies
├─ react-dom@16.7.0
├─ react-scripts@2.1.3
└─ react@16.7.0
info All dependencies
├─ react-dev-utils@7.0.1
├─ react-dom@16.7.0
├─ react-error-overlay@5.1.2
├─ react-scripts@2.1.3
└─ react@16.7.0
✨  Done in 11.64s.

Initialized a git repository.

Success! Created my-app at /private/tmp/react/my-app
Inside that directory, you can run several commands:

  yarn start
    Starts the development server.

  yarn build
    Bundles the app into static files for production.

  yarn test
    Starts the test runner.

  yarn eject
    Removes this tool and copies build dependencies, configuration files
    and scripts into the app directory. If you do this, you can’t go back!

We suggest that you begin by typing:

  cd my-app
  yarn start

Happy hacking!
       15.31 real        11.44 user        15.82 sys
```

</details>

<details><summary>Yarn Performance</summary>

```
andrei@macbookpro /t/react> yarn --version
1.13.0
andrei@macbookpro /t/react> time yarn create react-app my-app
yarn create v1.13.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...

success Installed "create-react-app@2.1.3" with binaries:
      - create-react-app

Creating a new React app in /private/tmp/react/my-app.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts...

yarn add v1.13.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 5 new dependencies.
info Direct dependencies
├─ react-dom@16.7.0
├─ react-scripts@2.1.3
└─ react@16.7.0
info All dependencies
├─ react-dev-utils@7.0.1
├─ react-dom@16.7.0
├─ react-error-overlay@5.1.2
├─ react-scripts@2.1.3
└─ react@16.7.0
✨  Done in 11.78s.

Initialized a git repository.

Success! Created my-app at /private/tmp/react/my-app
Inside that directory, you can run several commands:

  yarn start
    Starts the development server.

  yarn build
    Bundles the app into static files for production.

  yarn test
    Starts the test runner.

  yarn eject
    Removes this tool and copies build dependencies, configuration files
    and scripts into the app directory. If you do this, you can’t go back!

We suggest that you begin by typing:

  cd my-app
  yarn start

Happy hacking!
✨  Done in 16.99s.
       17.15 real        11.17 user        16.09 sys
```

</details>

Comparing the numbers they are at best the same and at worst npm is a bit faster.

What are you reasons for npm or for yarn?

After we reach a conclusion we'll decide on a migration policy.

**Comment by andreicek** [comment]
Upvote (:+1:) this comment for `yarn`.

**Comment by andreicek** [comment]
Upvote (:+1:) this comment for `npm`.

**Comment by DarkoKukovec** [comment]
On closer inspection, a lot of initial yarn benefits are gone - primarily speed and lock file.

From my perspective:
npm - has `npx` and `npm ci`, is built in into node, no need for separate install and upgrade process
yarn - workspaces - essential for monorepos, but in our case this is only datx and it's ok for it to be a special case.

**Comment by NinoMaj** [comment]
fyi, related to this discussion, https://github.com/yarnpkg/yarn/issues/6953
btw, yarn is second Facebook lib. first being Jest, that will transition from Flow, also by Facebook, to Typescript. I guess this battle is over, for now.

**Comment by andreicek** [comment]
@veksi is going to see this thru.

**Comment by veksi** [comment]
After doing some R&D I found out next:
1. There are no reliable tools for migrating from yarn to npm, or to be exact, create `package-lock.json` from `yarn.lock` file and keep consistency in module dependencies between those package managers. (There is some tool [synp](https://github.com/imsnif/synp), but never got it to work...)
2. All CRA projects should first be updated to CRA2 before even trying to switch to npm
  General steps:
  	1. Delete `lock` file and `node_modules` folder
    2. Bump `react-scripts` version to newest `2.1.3``
    3. Remove `eslint` from dependencies (`react-scripts` has its own `eslint` dependency `v. 5.6.0`)
    4. `npm i``

**POSSIBLE MIGRATION HELPER TOOL**

Possible tool for easier migration from yarn to npm may be [syncyarnlock](https://github.com/vasilevich/sync-yarnlock-into-packagejson#readme) which:
> Syncs yarn.lock versions into an exsisting package.json file, removing dynamic numbers such as with ^, keeping static versions intact.

General steps for migration using this tool would be:
1. Install tool using `npm install -g syncyarnlock`
2. Position inside project root and: `syncyarnlock`
3. Since most of the issues are caused by root level dependencies (since they trigger changes/installing new child dependencies) use this command to keep the list of all local root (level 0) dependencies (dependencies inside `node_modules`): `npm list --depth=0 > filename.txt`
4. Remove all lock files (`yarn.lock` in this case) and `node_modules` folder
5. Install new dependencies using: `npm i``

At this moment list of all local level 0 dependencies comes in hand if application start doesn't work since there might be mismatch between dependencies previously listed in `yarn.lock` and ones that are currently installed. 
Each issue/error generated by dependency changes need to be solved separately using google (yes I said it) and saved dependency list or/and old `yarn.lock` file.

Migration for smaller projects can be done without `syncyarnlock` with just keeping and eye on version which are being installed. -> brute force approach


Known issues with versions:

`NEXT.JS` projects which use version `7+` (`7.0.2` in my case) doesn't work with `webpack 4.25+`. To fix this either delete `webpack` from dependencies if you don't use it aside from `next.js` tasks (beacause `next.js`itself has webpack as dependency) or use verion `4.24.0` as it is the latest one working.

Using this steps I migrated few "smaller" projects to npm in reasonamble time but I would like to put this migration decision to vote since it's not straightforward task and might cause issues (take much more time) for bigger and complicated projects to be transfered.

**Comment by isBatak** [comment]
⚰️ npm_modules, yarn PnP ftw!

**Comment by DarkoKukovec** [comment]
Just now realised what @isBatak meant. Seems like a significant advantage for yarn: https://medium.freecodecamp.org/getting-rid-of-node-modules-with-yarn-plugn-play-a490e5e747d7

**Comment by andreicek** [comment]
Closing as stale for now. Will move the discussion to other channels.
